<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AYLink.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- ADB 客户端 -->
    <PackageReference Include="AdvancedSharpAdbClient" Version="3.6.16" />
    <!-- FFmpeg 解码 -->
    <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
    <!-- 日志 -->
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <!-- WebRTC 连接 -->
    <PackageReference Include="SIPSorcery" Version="10.0.3" />
  </ItemGroup>

</Project>
