<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AYLink.Controls</RootNamespace>
    <AssemblyName>AYLink.Controls</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="TabView\TabItem.axaml" />
    <AvaloniaResource Include="TabView\TabView.axaml" />
    <AvaloniaResource Include="Themes\BrowserTabViewTheme.axaml" />
    <AvaloniaResource Include="Terminal\Themes\Generic.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.2">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAvaloniaUI" Version="2.4.0" />
    <PackageReference Include="Unicode.net" Version="2.0.0" />
    <PackageReference Include="Wcwidth" Version="4.0.1" />
    <PackageReference Include="XTerm.NET" Version="1.0.12" />
  </ItemGroup>

</Project>
